routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', 'BaseController@home');
Route::get('/home', 'BaseController@home')->name('home');
Route::view('/search', 'base.search')->name('search');

Route::get('/user/search', 'UserController@search')->name('user.search');
Route::post('/user/search', 'UserController@search');

Route::get('/picture/search', 'PictureController@search')->name('picture.search');
Route::post('/picture/search', 'PictureController@search');

Route::get('download/{id}', 'PictureController@download')->name('download');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::view('/verified', 'auth.verified');
    Route::resource('picture', 'PictureController')->except('index', 'show');
    Route::resource('favorite', 'FavoriteController')->only('store', 'destroy');
});

Route::resource('picture', 'PictureController')->only('index', 'show');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/user/delete', 'UserController@del')->name('user.delete');
    Route::resource('user', 'UserController')->except('show', 'create', 'store');
    Route::get('/mypage', 'BaseController@mypage')->name('mypage');
});

Route::resource('user', 'UserController')->only('show');

app/Picture.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Picture extends Model
{
    // protected $table = 'pictures';

    protected $fillable = [
        'user_id', 'title', 'path', 'comment',
    ];

    public static $rules = [
        'title' => ['required', 'string', 'max:20'],
        'picture' => ['required', 'image', 'max:2048'],
        'comment' => ['max:100'],
    ];

    public function user() 
    {
        return $this->belongsTo('App\User');
    }

    public function favorites() 
    {
        return $this->hasMany('App\Favorite');
    }

    protected static function boot() 
    {
        parent::boot();
        static::deleting(function($model) {
            foreach($model->favorites as $favorite) {
                $favorite->delete();
            }
        });
    }
}

app/Http/Controllers/PictureController.php
<?php

namespace App\Http\Controllers;

use App\Picture;
use App\Favorite;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class PictureController extends Controller
{
    public function index()
    {
        $pictures = Picture::with('user')
                            ->orderBy('created_at', 'desc')
                            ->paginate(30);
        return view('picture.index', ['pictures' => $pictures]);
    }

    public function create()
    {
        $user = Auth::user();
        return view('picture.create', ['user' => $user]);
    }

    public function store(Request $request)
    {
        $this->validate($request, Picture::$rules);

        $pictureFile = $request->file('picture');
        $extension = $pictureFile->getClientOriginalExtension();

        do {
            $file_name = Str::random(20).'.'.$extension;
        } while (Picture::where('path', $file_name)->first() != null);

        $this->savePicture($pictureFile, $file_name);

        $form = $request->all();
        $form['path'] = $file_name;
        unset($form['_token']);
        unset($form['_method']);
        unset($form['picture']);
        $picture = Picture::create($form);
        return redirect(route('picture.show', ['picture' => $picture->id]));
    }

    public function show($id)
    {
        $picture = Picture::find($id);
        $user = Auth::user();

        if ($user == null) {
            $favorite = null;
        } else {
            $favorite = Favorite::where('user_id', $user->id)
                                ->where('picture_id', $picture->id)
                                ->first();
        }

        return view('picture.show', [
            'picture' => $picture, 
            'user' => $user, 
            'favorite' => $favorite
        ]);
    }

    public function edit($id)
    {
        $this->checkUser($id);
        
        $picture = Picture::find($id);
        return view('picture.edit', ['picture' => $picture]);
    }

    public function update($id, Request $request)
    {
        $this->checkUser($id);

        $this->validate($request, [
            'title' => ['required', 'string', 'max:20'],
            'comment' => ['max:100'],
        ]);

        $form = $request->all();
        unset($form['_token']);
        unset($form['_method']);
        unset($form['picture']);
        $picture = Picture::find($id);
        $picture->fill($form)->save();

        return redirect(route('picture.show', ['picture' => $picture->id]));
    }

    public function destroy($id)
    {
        $this->checkUser($id);

        $picture = Picture::find($id);

        if (Storage::exists('public/pictures/'.$picture->path)) {
            Storage::delete('public/pictures/'.$picture->path);
        }
        $picture->delete();

        return redirect('/mypage');
    }

    public function download($id) 
    {
        $picture = Picture::find($id);
        return Storage::download('public/pictures/'.$picture->path);
    }

    public function search(Request $request) 
    {
        $input = $request->input;
        if ($input == null) {
            $title = '画像を検索';
            $pictures = [];
            $input = '';
            $order = '';
        } else {
            $input = $this->blankToSpace($request->input);
            $title = '「'.$input.'」の結果';
            
            $order = $request->order;
            $pictures = Picture::with('user');
            switch ($order) {
                case '新しい順':
                    $pictures = $pictures->orderBy('updated_at', 'desc');
                    break;
                case '古い順':
                    $pictures = $pictures->orderBy('updated_at', 'asc');
                    break;
                case 'いいね順':
                    $pictures = $pictures->orderBy('favorite', 'desc');
                    break;
                default:
                    $pictures = $pictures->orderBy('updated_at', 'desc');
            }
            
            if ($input != null)  {
                $keys = explode(' ', $input);
                foreach ($keys as $key) {
                    $pictures = $pictures->where('title', 'like', '%'.$key.'%');
                }
            }
            $pictures = $pictures->paginate(30);
        }

        return view('picture.search', [
            'title' => $title, 
            'pictures' => $pictures, 
            'input' => $input, 
            'order' => $order
        ]);
    }

    private function checkUser($picture_id) 
    {
        $user = Auth::user();
        if ($user == null || $user->id != Picture::find($picture_id)->user_id) {
            abort(403);
        }
    }

    private function savePicture($image, $file_name) 
    {
        // get instance
        $img = \Image::make($image);
        // resize
        $img->fit(512, null, function($constraint){
            $constraint->upsize(); 
        });
        // save
        $save_path = 'public/pictures/'.$file_name;
        Storage::put($save_path, (string) $img->encode());
    }
}

resources/views/picture/create.blade.php
@extends('layouts.layout')

@section('title', full_title('投稿'))

@section('content')
  <div class="post-picture">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <form method="post" action="{{ route('picture.store') }}" enctype="multipart/form-data">
            @csrf

            <input type="hidden" name="user_id" value="{{ $user->id }}">

            <div class="row justify-content-center" id="picture">
            </div>

            <div class="form-group row justify-content-center" style="margin-bottom: 0;">
              <label for="picture-input" class="btn btn-light @error('picture') is-invalid @enderror">
                写真を選択
                <input id="picture-input" type="file" name="picture" onchange="previewImage(this);">
              </label>
            </div>
            
            <div class="row justify-content-center">
              @error('picture')
                <span style="color: #e3342f; font-size: 12px; margin: 0 0 16px;" role="alert">
                  <strong>{{ $errors->first('picture') }}</strong>
                </span>
              @enderror
            </div>

            <div class="form-group row">
              <div class="col-md-4 text-md-right">
                <label for="title">タイトル</label>
              </div>

              <div class="col-md-8">
                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}">

                @error('title')
                  <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
            </div>

            <div class="form-group row">
              <div class="col-md-4 text-md-right">
                <label for="title">コメント</label>
              </div>
              
              <div class="col-md-8">
                <textarea class="form-control @error('comment') is-invalid @enderror" name="comment">{{ old('comment') }}</textarea>

                @error('comment')
                  <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
            </div>

            <div class="form-group row">
              <div class="col-md-6 offset-md-3 text-center">
                <button type="submit" class="btn btn-primary">
                  投稿
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script>
    function previewImage(obj)
    {
      if (document.getElementById('img') === null) {
        const img = document.createElement('img');
        img.src = "";
        img.id = "img";
        document.getElementById("picture").appendChild(img);
      }
      var fileReader = new FileReader();
      fileReader.onload = (function() {
        document.getElementById('img').src = fileReader.result;
      });
      fileReader.readAsDataURL(obj.files[0]);
    }
  </script>
@endsection

resources/views/picture/edit.blade.php
@extends('layouts.layout')

@section('title', full_title('「'.$picture->title.'」の編集'))

@section('content')
<div class="post-picture">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <form method="post" action="{{ route('picture.update', ['picture' => $picture->id]) }}" enctype="multipart/form-data">
          @csrf
          @method('PATCH')

          <input type="hidden" name="user_id" value="{{ $picture->user->id }}">

          <div class="row justify-content-center" id="picture">
            <img src="{{ asset('storage/pictures/'.$picture->path) }}" id="img">
          </div>

          <div class="form-group row">
            <div class="col-md-4 text-md-right">
              <label for="title">タイトル</label>
            </div>

            <div class="col-md-8">
              <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="@if(old('title') == null){{ $picture->title }}@else{{ old('title') }}@endif">

              @error('title')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-4 text-md-right">
              <label for="title">コメント</label>
            </div>
            
            <div class="col-md-8">
              <textarea class="form-control @error('comment') is-invalid @enderror" name="comment">@if(old('comment') == null){{ $picture->comment }}@else{{ old('comment') }}@endif</textarea>

              @error('comment')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-6 offset-md-3 text-center">
              <button type="submit" class="btn btn-primary">
                編集
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/picture/index.blade.php
@extends('layouts.layout')

@section('title', full_title('トレンド'))

@section('content')
  <div class="posts">
    <h1>トレンド</h1>

    {{ $pictures->onEachSide(2)->links() }}

    @foreach ($pictures as $picture)
    <section class="post">
      <h1>{{ $picture->title }}</h1>

      <a href="{{ route('picture.show', ['picture' => $picture->id]) }}"><img src="{{ asset('storage/pictures/'.$picture->path) }}"></a>
      
      <div class="creater">
        @if($picture->user == null)
        <img><i>退会したユーザー</i>
        @else
        <img src="{{ asset('storage/profiles/'.$picture->user->profile_image) }}">
        <a href="{{ route('user.show', ['user' => $picture->user_id]) }}">{{ $picture->user->name }}</a>
        @endif
      </div>
    </section>
    @endforeach

    {{ $pictures->onEachSide(2)->links() }}
    
  </div>
@endsection

resources/views/picture/search.blade.php
@extends('layouts.layout')

@section('title', full_title($title))


@section('content')
  <div class="search container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h1>画像を検索</h1>
        <form method="get" action="{{ route('picture.search') }}">
          @csrf

          <div class="row m-1 form-group">
            <div class="col-9 p-0">
              <input type="text" name="input" value="{{ $input }}" class="form-control">
            </div>
            <div class="col-3 p-0 text-center">
              <button class="btn btn-primary">検索</button>
            </div>
          </div>
          
          <div class="row m-1 form-group">
            <div class="col-9 p-0">
              <select name="order" class="form-control">
                <option value="新しい順" @if ($order == "新しい順") selected @endif>新しい順</option>
                <option value="古い順" @if ($order == "古い順") selected @endif>古い順</option>
                <option value="いいね順" @if ($order == "いいね順") selected @endif>いいね順</option>
              </select>
            </div>
          </div>
        </form>

        @if ($title != '画像を検索')
        <h1>{{ $title }}</h1>

        <div class="posts">
          {{ $pictures->appends(['input'=>$input, 'order'=>$order])->onEachSide(2)->links() }}

          @foreach ($pictures as $picture)
          <section class="post">
            <h1>{{ $picture->title }}</h1>

            <a href="{{ route('picture.show', ['picture' => $picture->id]) }}"><img src="{{ asset('storage/pictures/'.$picture->path) }}"></a>

            <div class="favorite">
              いいね:{{ $picture->favorite }}
            </div>
            
            <div class="creater">
              @if($picture->user == null)
              <img><i>退会したユーザ</i>
              @else
              <img src="{{ asset('storage/profiles/'.$picture->user->profile_image) }}">
              <a href="{{ route('user.show', ['user' => $picture->user_id]) }}">{{ $picture->user->name }}</a>
              @endif
            </div>
          </section>
          @endforeach

          {{ $pictures->appends(['input'=>$input, 'order'=>$order])->onEachSide(2)->links() }}
        </div>
        @else
        キーワードを入力してください
        @endif
      </div>
    </div>
  </div>
@endsection

resources/views/picture/show.blade.php
@extends('layouts.layout')

@section('title', full_title($picture->title))

@section('content')
<div class="show-picture">
  <div class="container">
    <div class="row justify-content-center title">
      <h1>{{ $picture->title }}</h1>
    </div>
    <div class="row justify-content-center picture">
      <img src="{{ asset('storage/pictures/'.$picture->path) }}" alt="画像">
    </div>

    @isset($picture->comment)
    <div class="row justify-content-center comment">
      <p><i>{!! nl2br($picture->comment) !!}</i></p>
    </div>
    @endisset

    <div class="row justify-content-start favorite">
      いいね:{{ $picture->favorite }}
    </div>

    <div class="row justify-content-start creater">
      @if($picture->user == null)
      <img><i>退会したユーザ</i>
      @else
      <img src="{{ asset('storage/profiles/'.$picture->user->profile_image) }}">
      <a href="{{ route('user.show', ['user' => $picture->user_id]) }}">{{ $picture->user->name }}</a>
      @endif
    </div>

    @auth
    @if ($favorite == null)
    <div class="row justify-content-center actions">
      <a href="" onclick="document.favorite_form.submit(); return false">いいね</a>

      <form name="favorite_form" type="hidden" method="post" action="{{ route('favorite.store') }}">
        @csrf
        <input type="hidden" name="user_id" value="{{ $user->id }}">
        <input type="hidden" name="picture_id" value="{{ $picture->id }}">
      </form>
    </div>
    @else
    <div class="row justify-content-center actions favorited">
      <a href="" onclick="document.delete_favorite_form.submit(); return false">いいね済</a>

      <form name="delete_favorite_form" type="hidden" method="post" action="{{ route('favorite.destroy', ['favorite' => $favorite->id]) }}">
        @csrf
        @method('DELETE')
      </form>
    </div>
    @endif
    @endauth

    <div class="row justify-content-center download">
      <a href="{{ route('download', ['id' => $picture->id]) }}">ダウンロード</a>
    </div>

    @if ($user != null && $picture->user_id == $user->id)
    <div class="row justify-content-center actions">
      <a href="{{ route('picture.edit', ['picture' => $picture->id]) }}">編集</a>
    </div>
    
    <div class="row justify-content-center actions">
      <a href="" onclick="javascript:if(confirm('本当に削除しますか？')) { document.delete_form.submit(); } return false">削除</a>

      <form type="hidden" name="delete_form" method="post" action="{{ route('picture.destroy', ['picture' => $picture->id]) }}">
        @csrf
        @method('DELETE')
      </form>
    </div>
    @endif
  </div>
</div>
@endsection