routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', 'BaseController@home');
Route::get('/home', 'BaseController@home')->name('home');
Route::view('/search', 'base.search')->name('search');

Route::get('/user/search', 'UserController@search')->name('user.search');
Route::post('/user/search', 'UserController@search');

Route::get('/picture/search', 'PictureController@search')->name('picture.search');
Route::post('/picture/search', 'PictureController@search');

Route::get('download/{id}', 'PictureController@download')->name('download');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::view('/verified', 'auth.verified');
    Route::resource('picture', 'PictureController')->except('index', 'show');
    Route::resource('favorite', 'FavoriteController')->only('store', 'destroy');
});

Route::resource('picture', 'PictureController')->only('index', 'show');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/user/delete', 'UserController@del')->name('user.delete');
    Route::resource('user', 'UserController')->except('show', 'create', 'store');
    Route::get('/mypage', 'BaseController@mypage')->name('mypage');
});

Route::resource('user', 'UserController')->only('show');

app/Http/Controllers/BaseController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Picture;

class BaseController extends Controller
{
    public function home() 
    {
        $pictures = Picture::with('user')
                            ->orderBy('created_at', 'desc')
                            ->paginate(20);
        return view('base.home', ['pictures' => $pictures]);
    }

    public function mypage() 
    {
        $user = Auth::user();
        $pictures = Picture::orderBy('created_at', 'desc')
                            ->where('user_id', $user->id)
                            ->paginate(10);
        return view('base.mypage', ['user' => $user, 'pictures' => $pictures]);
    }
}

resources/views/base/home.blade.php
@extends('layouts.layout')

@section('title', full_title('Home'))

@section('content')
    <section>
        <h1>PicGalleryとは</h1>
        <p>PicGalleryは、写真や画像を投稿または提供するサイトです。</p>
        <p>主な用途は、個人の作品の公開や自由素材の提供を想定しています。</p>
    </section>

    <section>
        <h1>注意事項</h1>
        <p>アップロードする際は、個人を特定できるような情報が映し出されていないか、各個人で確認してください。</p>
        <p>また、アップロードされた作品は他人に使用され得るということを十分理解してください。</p>
    </section>

    @auth
    @else
    <section>
        <h1>新規登録</h1>
        <p>アカウントを持っていない方は<a href={{ route('register') }}>こちら</a>から。</p>
    </section>

    <section>
        <h1>ログイン</h1>
        <p>写真・画像を投稿するためには<a href={{ route('login') }}>ログイン</a>する必要があります。</p>
    </section>
    @endauth

    <section class="posts">
        <h1 class="trend"><a href="{{ route('picture.index') }}">トレンド</a></h1>

        {{ $pictures->onEachSide(2)->links() }}

        @foreach ($pictures as $picture)
        <section class="post">
            <h1>{{ $picture->title }}</h1>
            
            <a href="{{ route('picture.show', ['picture' => $picture->id]) }}"><img src="{{ asset('storage/pictures/'.$picture->path) }}"></a>

            <div class="favorite">
                いいね:{{ $picture->favorite }}
            </div>

            <div class="creater">
                @if($picture->user == null)
                <img><i>退会したユーザ</i>
                @else
                <img src="{{ asset('storage/profiles/'.$picture->user->profile_image) }}">
                <a href="{{ route('user.show', ['user' => $picture->user_id]) }}">{{ $picture->user->name }}</a>
                @endif
            </div>
        </section>
        @endforeach

        {{ $pictures->onEachSide(2)->links() }}

    </section>
@endsection

resources/views/base/mypage.blade.php
@extends('layouts.layout')

@section('title', full_title('マイページ'))

@section('content')
  <div class="profile container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            プロフィール
          </div>
          <div class="card-body">
            <img src="{{ asset('storage/profiles/'.$user->profile_image) }}" alt="プロフィール画像">
            <div class="name">
              {{ $user->name }}
            </div>

            @isset ($user->body)
            <div class="body">
              {!! nl2br($user->body) !!}
            </div>
            @endisset

            <a href="{{ route('user.edit', ['user' => $user->id]) }}">プロフィールを編集する</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <section>
    <h1>退会</h1>
    <p>退会する方は<a href="{{ route('user.delete') }}">こちら</a>から</p>
  </section>

  <section class="myposts">
    <h1>投稿した写真・画像</h1>

    {{ $pictures->onEachSide(2)->links() }}

    @foreach ($pictures as $picture)
      <div class="post">
        <h2>{{ $picture->title }}</h2>

        <a href="{{ route('picture.show', ['picture' => $picture->id]) }}"><img src="{{ asset('storage/pictures/'.$picture->path) }}" alt="投稿画像"></a>

        <div class="favorite">
          いいね:{{ $picture->favorite }}
        </div>
      </div>
    @endforeach

    {{ $pictures->onEachSide(2)->links() }}

  </section>
@endsection

resources/views/base/search.blade.php
@extends('layouts.layout')

@section('title', full_title('検索'))

@section('content')
  <div class="search container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="row justify-content-center"><a href="{{ route('picture.search') }}">画像を検索</a></div>
        <div class="row justify-content-center"><a href="{{ route('user.search') }}">ユーザーを検索</a></div>
      </div>
    </div>
  </div>
@endsection