routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', 'BaseController@home');
Route::get('/home', 'BaseController@home')->name('home');
Route::view('/search', 'base.search')->name('search');

Route::get('/user/search', 'UserController@search')->name('user.search');
Route::post('/user/search', 'UserController@search');

Route::get('/picture/search', 'PictureController@search')->name('picture.search');
Route::post('/picture/search', 'PictureController@search');

Route::get('download/{id}', 'PictureController@download')->name('download');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::view('/verified', 'auth.verified');
    Route::resource('picture', 'PictureController')->except('index', 'show');
    Route::resource('favorite', 'FavoriteController')->only('store', 'destroy');
});

Route::resource('picture', 'PictureController')->only('index', 'show');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/user/delete', 'UserController@del')->name('user.delete');
    Route::resource('user', 'UserController')->except('show', 'create', 'store');
    Route::get('/mypage', 'BaseController@mypage')->name('mypage');
});

Route::resource('user', 'UserController')->only('show');

app/User.php
<?php

namespace App;

use App\Notifications\VerifyEmailNotification;
use App\Notifications\ResetPasswordNotification;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'profile_image', 'body'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function pictures() 
    {
        return $this->hasMany('App\Picture');
    }

    public function favorites() 
    {
        return $this->hasMany('App\Favorite');
    }

    public function sendEmailVerificationNotification()
    {
        $this->notify(new VerifyEmailNotification());
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\Picture;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    public function show($id) 
    {
        $user = User::find($id);
        $pictures = Picture::orderBy('created_at', 'desc')
                            ->where('user_id', $user->id)
                            ->paginate(10);
        return view('user.show', ['user' => $user, 'pictures' => $pictures]);
    }

    public function edit($id) 
    {
        $this->checkUser($id);
        
        $user = Auth::user();
        return view('user.edit', ['user' => $user]);
    }

    public function update($id, UserRequest $request) 
    {
        $this->checkUser($id);

        $profileImage = $request->file('profile_image');
        
        $form = $request->all();
        if ($profileImage != null) {
            $form['profile_image'] = $this->saveProfileImage($profileImage, $id); // return file name
        }
        unset($form['_token']);
        unset($form['_method']);
        $user = Auth::user();
        $user->fill($form)->save();
        return redirect('/mypage');
    }

    public function del() 
    {
        $user = Auth::user();
        return view('user.del', ['user' => $user]);
    } 

    public function destroy($id) 
    {
        $this->checkUser($id);
        
        $user = Auth::user();
        if ($user->profile_image != 'default.png' && Storage::exists('public/profiles/'.$user->profile_image)) {
            Storage::delete('public/profiles/'.$user->profile_image);
        }
        $user->delete();

        return redirect('/home');
    }
    
    public function search(Request $request) 
    {
        $input = $request->input;
        if ($input == null) {
            $title = 'ユーザーを検索';
            $users = [];
            $input = '';
        } else {
            $input = $this->blankToSpace($input);
            $title = '「'.$input.'」の結果';

            $users = User::orderBy('created_at', 'desc');
            if ($input != null)  {
                $keys = explode(' ', $input);
                foreach ($keys as $key) {
                    $users = $users->where('name', 'like', '%'.$key.'%');
                }
            }
            $users = $users->paginate(30);
        }

        return view('user.search', [
            'title' => $title, 
            'users' => $users, 
            'input' => $input
        ]);
    }

    private function checkUser($user_id) 
    {
        $user = Auth::user();
        if ($user == null || $user->id != $user_id) {
            abort(403);
        }
    }

    private function saveProfileImage($image, $id) 
    {
        // get instance
        $img = \Image::make($image);
        // resize
        $img->fit(100, 100, function($constraint){
            $constraint->upsize(); 
        });
        // save
        $file_name = 'profile_'.$id.'.'.$image->getClientOriginalExtension();
        $save_path = 'public/profiles/'.$file_name;
        Storage::put($save_path, (string) $img->encode());

        return $file_name;
    }
}

resources/views/user/del.blade.php
@extends('layouts.layout')

@section('title', full_title('退会'))

@section('content')
<div class="profile container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card destroy-user">
        <div class="card-header">
          退会
        </div>
        <div class="card-body">
          <p>退会する場合、以下の事項に注意してください。</p>
          <ul>
            <li>退会後でも投稿した写真・画像は残ります。</li>
            <li>削除されたアカウントは復元できません。</li>
          </ul>
          <p>以上を了解した上で下のボタンをクリックしてください。</p>
          <form method="post" action="{{ route('user.destroy', ['user'=>$user->id]) }}">
            @csrf
            @method('DELETE')
            <button class="btn btn-primary" onclick="return confirm('本当に退会しますか？')" >退会する</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.layout')

@section('title', full_title('プロフィール編集'))
    
@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">プロフィール編集</div>
          <div class="card-body">
            <form method="post" action="{{ route('user.update', ['user' => $user->id]) }}" enctype="multipart/form-data">
              @csrf
              @method('PATCH')

              <div class="form-group row">
                <label for="profile_image" class="col-md-4 col-form-label text-md-right">プロフィール画像</label>

                <div class="col-md-6 align-self-center">
                  <label for="profile_image" class="btn"><img src="{{ asset('storage/profiles/'.$user->profile_image) }}" id="img">
                    <input id="profile_image" type="file" class="@error('profile_image') is-invalid @enderror" name="profile_image" onchange="previewImage(this);">
                  </label>

                  @error('profile_image')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
                  @enderror
                </div>
              </div>

              <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">名前</label>

                <div class="col-md-6">
                  <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="@if(old('name') != null){{ old('name') }}@else{{ $user->name }}@endif" required autocomplete="name" autofocus>

                  @error('name')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
                  @enderror
                </div>
              </div>

              <div class="form-group row">
                <label for="email" class="col-md-4 col-form-label text-md-right">メールアドレス</label>

                <div class="col-md-6">
                  <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="@if (old('email') != null) {{ old('email') }} @else {{ $user->email }} @endif" required autocomplete="email">

                  @error('email')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>

              <div class="form-group row">
                <label for="body" class="col-md-6 offset-md-3 col-form-label text-md-center">自己紹介文</label>
              </div>

              <div class="form-group row">
                <div class="col-md-10 offset-md-1">

                  <textarea id="body" class="form-control @error('body') is-invalid @enderror" name="body">@if (old('body') != null){{ old('body') }}@else{{ $user->body }}@endif</textarea>
                  @error('body')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>

              <div class="form-group row">
                <div class="col-md-6 offset-md-3 text-center">
                  <button type="submit" class="btn btn-primary">
                    変更
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script>
    function previewImage(obj)
    {
      var fileReader = new FileReader();
      fileReader.onload = (function() {
        document.getElementById('img').src = fileReader.result;
      });
      fileReader.readAsDataURL(obj.files[0]);
    }
  </script>
@endsection

resources/views/user/search.blade.php
@extends('layouts.layout')

@section('title', full_title($title))


@section('content')
  <div class="search container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h1>ユーザーを検索</h1>
        <form method="get" action="{{ route('user.search') }}">
          @csrf

          <div class="row m-1 form-group">
            <div class="col-9 p-0">
              <input type="text" name="input" value="{{ $input }}" class="form-control">
            </div>

            <div class="col-3 p-0 text-center">
              <button class="btn btn-primary">検索</button>
            </div>
          </div>
        </form>

        @if ($title != 'ユーザーを検索')
        <h1>{{ $title }}</h1>
        
        <div class="users">
          {{ $users->appends(['input'=>$input])->onEachSide(2)->links() }}

          <table class="table">
            <thead>
              <tr><th>ユーザー名</th></tr>
            </thead>
            <tbody>
              @foreach ($users as $user)
                <tr>
                  <td>
                    <img src="{{ asset('storage/profiles/'.$user->profile_image) }}">　<a href="{{ route('user.show', ['user' => $user->id]) }}">{{ $user->name }}</a>
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
          
          {{ $users->appends(['input'=>$input])->onEachSide(2)->links() }}
        </div>
        @else
        キーワードを入力してください
        @endif

      </div>
    </div>
  </div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.layout')

@section('title', full_title($user->name))

@section('content')
  <div class="profile container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card profile">
          <div class="card-header">
            プロフィール
          </div>
          <div class="card-body">
            <img src="{{ asset('storage/profiles/'.$user->profile_image) }}" alt="プロフィール画像">

            <div class="name">
              {{ $user->name }}
            </div>

            @isset ($user->body)
            <div class="body">
              {!! nl2br($user->body) !!}
            </div>
            @endisset
          </div>
        </div>
      </div>
    </div>
  </div>

  <section class="myposts">
    <h1>投稿した写真・画像</h1>

    {{ $pictures->onEachSide(2)->links() }}

    @foreach ($pictures as $picture)
      <div class="post">
        <h2>{{ $picture->title }}</h2>

        <a href="{{ route('picture.show', ['picture' => $picture->id]) }}"><img src="{{ asset('storage/pictures/'.$picture->path) }}" alt="投稿画像"></a>

        <div class="favorite">
          いいね:{{ $picture->favorite }}
        </div>
      </div>
    @endforeach
    
    {{ $pictures->onEachSide(2)->links() }}
  </section>
@endsection